# Generated by Django 3.1.5 on 2021-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('accesskey', models.CharField(max_length=100)),
                ('secretaccesskey', models.CharField(max_length=100)),
            ],
        ),
    ]
