# Generated by Django 3.1.5 on 2021-02-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymodel',
            name='region',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
