# Generated by Django 3.1.6 on 2021-03-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_networkinterfacemodel_subnetmodel_vpcmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterfacemodel',
            name='subnetid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
