# Generated by Django 3.1.6 on 2021-03-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0006_networkinterfacemodel_subnetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancemodel',
            name='netint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
